apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-test-vm-new
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: fedora-test-vm-new
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
      volumes:
      - name: containerdisk
        containerDisk:
          image: kubevirt/fedora-cloud-container-disk-demo:latest
