apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-installation
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubevirt
  project: default
  source:
    repoURL: 'https://github.com/MahamedYahye/kubevirt'
    path: example.yaml  # Dit is het pad naar het YAML-bestand binnen je Git repository
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  namespace: kubevirt
